import fs from "node:fs";

import yargs from "yargs";
import { hideBin } from "yargs/helpers";
import { exportDatabase } from "./exportNotion";
import generateFeed from "./feed";
import { dumpSinglePost, getDumpPosts, writeDump } from "./io";
import { lintPosts } from "./lint";
import { logger } from "./logger";
import { generateRedirect } from "./migration";
import generateOgImages from "./og";
import { fetchOrcidProfile } from "./orcid";
import { template } from "./template";

yargs(hideBin(process.argv))
  .scriptName("post-utils")
  .usage("$0 <cmd> [args]")
  .command(
    "dump",
    "Dump markdown file into json",
    (yargs) => {
      yargs.positional("mdDir", {
        type: "string",
        describe: "Root directory of the markdown files",
      });

      yargs.positional("imageDist", {
        type: "string",
        describe: "",
      });

      yargs.positional("output", {
        type: "string",
        describe: "",
        alias: ["o", "out"],
      });

      yargs.demandOption(["mdDir", "imageDist", "output"]);
    },
    async (argv) => {
      const mdDir = argv.mdDir as string;
      const imageDist = argv.imageDist as string;
      const output = argv.output as string;
      logger.info({ mdDir, imageDist, output }, "Starting dump");
      const dumpPosts = await getDumpPosts(mdDir, imageDist);
      await writeDump(output, dumpPosts);
      logger.info({ count: dumpPosts.length, output }, "Dump complete");
    },
  )
  .command(
    "dump-file",
    "Dump a single markdown file into json (for debugging)",
    (yargs) => {
      yargs.positional("file", {
        type: "string",
        describe: "Path to the markdown file",
      });

      yargs.positional("imageDist", {
        type: "string",
        describe: "Destination directory for optimized images",
      });

      yargs.option("output", {
        type: "string",
        describe: "Output file path (defaults to stdout)",
        alias: ["o", "out"],
      });

      yargs.demandOption(["file", "imageDist"]);
    },
    async (argv) => {
      const file = argv.file as string;
      const imageDist = argv.imageDist as string;
      const output = argv.output as string | undefined;

      const result = await dumpSinglePost(file, imageDist);

      const json = JSON.stringify(result, null, 2);
      if (output) {
        const { writeFile: writeFileAsync } = await import("node:fs/promises");
        await writeFileAsync(output, json);
        logger.info({ output }, "Single post dump written to file");
      } else {
        process.stdout.write(`${json}\n`);
      }
    },
  )
  .command(
    "rss",
    "generate rss feed for blog",
    (yargs) => {
      yargs.positional("dump", {
        type: "string",
        describe: "dump file generated by post-utils dump",
      });
      yargs.positional("dst", {
        type: "string",
        describe: "destination dir to generate rss feed",
      });

      yargs.demandOption(["dump", "dst"]);
    },
    async (argv) => {
      const dump = argv.dump as string;
      const dst = argv.dst as string;
      logger.info({ dump, dst }, "Generating RSS feed");
      await generateFeed(dump, dst);
      logger.info({ dst }, "RSS feed generation complete");
    },
  )
  .command(
    "og",
    "Generate OG images for all posts",
    (yargs) => {
      yargs.positional("dump", {
        type: "string",
        describe: "dump file generated by post-utils dump",
      });
      yargs.positional("dst", {
        type: "string",
        describe: "destination directory for OG images",
      });
      yargs.positional("prefix", {
        type: "string",
        describe: "URL prefix (techblog or paperstream)",
      });
      yargs.positional("fontDir", {
        type: "string",
        describe: "directory containing font files",
      });
      yargs.demandOption(["dump", "dst", "prefix", "fontDir"]);
    },
    async (argv) => {
      await generateOgImages(
        argv.dump as string,
        argv.dst as string,
        argv.prefix as string,
        argv.fontDir as string,
      );
    },
  )
  .command(
    "template",
    "write blog template",
    (yargs) => {
      yargs.positional("output", {
        type: "string",
        describe: "",
        alias: ["o", "out"],
      });
      yargs.option("tags", {
        type: "string",
        array: true,
        describe: "tags for the post",
        alias: "t",
      });
      yargs.demandOption(["output"]);
    },
    (argv) => {
      const tags = argv.tags as string[] | undefined;
      fs.writeFileSync(argv.output as string, template(tags));
    },
  )
  .command(
    "migration",
    "migration utils",
    (yargs) => {
      yargs.positional("src", { type: "string", describe: "posts src" });
      yargs.demand("src");
    },
    async (argv) => {
      const result = await generateRedirect(argv.src as string);
      logger.info({ result }, "Migration redirect generated");
    },
  )
  .command(
    "lint",
    "Lint markdown posts for common issues",
    (yargs) => {
      yargs.positional("src", {
        type: "string",
        describe: "Root directory of the markdown files to lint",
      });
      yargs.demandOption(["src"]);
    },
    async (argv) => {
      const src = argv.src as string;
      const errors = await lintPosts(src);

      if (errors.length > 0) {
        for (const error of errors) {
          const location =
            error.line != null ? `:${error.line}:${error.column ?? 1}` : "";
          logger.error(
            { file: error.file, rule: error.ruleId },
            `${error.file}${location}: ${error.message}`,
          );
        }
        logger.error(
          { count: errors.length },
          `Found ${errors.length} lint error(s)`,
        );
        process.exit(1);
      }

      logger.info("No lint errors found");
    },
  )
  .command(
    "orcid",
    "Fetch ORCID profile data and dump to JSON",
    (yargs) => {
      yargs.positional("orcidId", {
        type: "string",
        describe: "ORCID ID (e.g. 0000-0002-3066-2940)",
      });
      yargs.positional("output", {
        type: "string",
        describe: "Output JSON file path",
        alias: ["o", "out"],
      });
      yargs.demandOption(["orcidId", "output"]);
    },
    async (argv) => {
      const orcidId = argv.orcidId as string;
      const output = argv.output as string;
      logger.info({ orcidId, output }, "Starting ORCID profile dump");
      const profile = await fetchOrcidProfile(orcidId);
      const { writeFile } = await import("node:fs/promises");
      await writeFile(output, JSON.stringify(profile, null, 2));
      logger.info({ output }, "ORCID profile dump complete");
    },
  )
  .command(
    "paper-stream",
    "notion paper stream export",
    (yargs) => {
      yargs.positional("databaseId", {
        type: "string",
        describe: "database id",
      });
      yargs.positional("publicDir", { type: "string", describe: "public dir" });
      yargs.positional("outputDir", { type: "string", describe: "output dir" });
    },
    async (argv) => {
      await exportDatabase(
        argv.databaseId as string,

        (o) => {
          // @ts-expect-error
          if (o.properties.Status.select === null) {
            return false;
          }

          // @ts-expect-error
          return o.properties.Status.select.name === "Done";
        },
        argv.publicDir as string,
        argv.outputDir as string,
      );
    },
  )
  .fail((msg, err) => {
    if (err) {
      logger.fatal({ err }, "Command failed");
    } else if (msg) {
      logger.error({ msg }, "Invalid usage");
    }
    process.exit(1);
  })
  .help()
  .parse();
