name: Actionlint

on:
  pull_request:
    paths:
      - ".github/workflows/*"
      - ".github/actions/*"

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install mise
        uses: jdx/mise-action@v2
      - name: Run actionlint
        run: actionlint --color
