name: bedtools CI

on:
  push

jobs: 
  DockerBuildCI:
    runs-on: "ubuntu-latest"

    steps:
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ github.ref }}-${{ github.sha }}
            ${{ github.ref }}
            refs/head/main
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: create tag
        shell: bash
        run: |
          SHA=${{ github.sha }}
          TAG=${{ inputs.username }}/${{ inputs.image_name }}:$(TZ=UTC-9 date '+%Y%m')-${SHA:0:7}
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            LATEST=${{ inputs.username }}/${{ inputs.image_name }}:latest
            echo "TAGS=$TAG,$LATEST" >> $GITHUB_ENV
            echo "TAG=$TAG" >> $GITHUB_ENV
          else
            echo "TAGS=$TAG" >> $GITHUB_ENV
            echo "TAG=$TAG" >> $GITHUB_ENV
          fi
          echo TAG $TAG
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.standalone
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: ${{ env.TAGS }}