name: node CI

on:
  push

permissions:
  contents: read

jobs:
  NodeCI:
    runs-on: "ubuntu-latest"
    timeout-minutes: 30
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: true
          persist-credentials: false

      - name: install mise
        uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3.6.3

      - run: pnpm i

      - uses: ./.github/actions/setup-playwright

      - run: pnpm lint
      - run: pnpm test
