name: node CI

on:
  push

jobs:
  NodeCI:
    runs-on: "ubuntu-latest"

    steps:
      - name: install mise
        uses: jdx/mise-action@v2
        with:
          experimental: true

      - run: pnpm i
      - run: pnpm lint
      - run: pnpm test
