name: node CI

on:
  push

permissions:
  contents: read

jobs:
  NodeCI:
    runs-on: "ubuntu-latest"
    timeout-minutes: 30
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: true
          persist-credentials: false

      - name: install mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1

      - run: pnpm install --frozen-lockfile

      - uses: ./.github/actions/setup-playwright

      - run: pnpm lint
      - run: pnpm test
