name: node CI

on:
  push

jobs:
  NodeCI:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: install mise
        uses: jdx/mise-action@v2

      - run: pnpm i
      - run: pnpm lint
      - run: pnpm test
