name: Cron for paper-stream update PR

on:
  push

jobs:
  CreatePaperStreamPR:
    runs-on: "ubuntu-latest"
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: install mise
        uses: jdx/mise-action@v2

      - run: pnpm i

      - name: build cli
        run: pnpm cli:build

      - name: paper-stream
        run: pnpm cli:paper-stream

      - name: format markdown
        run: dprint fmt

      - name: commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ci: auto commit at $(date -u +'%Y-%m-%dT%H:%M:%SZ')"

      - name: create PR if diff exists
        run: |
          if ! git diff --exit-code; then
            gh pr create \
              --title "Auto commit of paper-stream at $(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
              --base main \
              --body "This PR was created automatically."
          fi
