name: Build docker

on:
  push

jobs: 
  DockerBuildCI:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile.standalone
