name: Build docker

on:
  push

jobs: 
  DockerBuildCI:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      
      - name: meilisearch
        run: docker compose -f docker-compose.test.yml up -d

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile.standalone
          build-args: |
            MEILISEARCH_URL="host.docker.internal:7700"
          add-hosts: |
            host.docker.internal:host-gateway

