name: web build

on:
  pull_request:
    paths:
      - "web/**"
      - posts/**
      - ".github/workflows/web-build.yaml"
  push:
    branches:
      - main
    paths:
      - "web/**"
      - posts/**
      - ".github/workflows/web-build.yaml"

jobs:
  web-build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: true

      - name: install mise
        uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3.6.3

      - name: trust
        run: mise trust -P .mise.toml

      - name: install deps
        run: pnpm i

      - name: build cli
        run: pnpm cli:build

      - name: build web
        run: pnpm web-build

      - name: install playwright browsers
        run: cd web && npx playwright install --with-deps chromium

      - name: run e2e tests
        run: cd web && pnpm test:e2e

      # mise trustが必要というエラーが出るが、なんで出るのかわからない
      # 削除するとmise trustはいらないので、一旦削除
      - name: hack
        run: rm -rf .mise.toml

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy web/out --project-name=site --branch=${{ github.head_ref || github.ref_name }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
